//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kindergarten.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Child
    {
        public int ID { get; set; }
        public string Surname { get; set; }
        public string Firstname { get; set; }
        public string Patronymic { get; set; }
        public string Fullname => $"{Surname} {Firstname} {Patronymic}";
        public int IDParent { get; set; }
        public Nullable<int> IDGroup { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Parent Parent { get; set; }
    }
}
